spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    
gateway:
  ip: 172.18.0.5

order_service:
#   url: http://ORDER-SERVICE/order-service/%s/orders
  url: atuator test
  exception:
    order_is_empty: User's order is Empty
